### PR TITLE
Add HFSP mode 0: Disable Fan

### PR DESCRIPTION
**Pull request by Charlyo**
I Know this state might actually be harmful for the laptop, but IMHO that option should be user selectable.

### CODE REVIEW

**Comment by zhen-zen** [comment]
Personally I prefer to enable it via a checkbox in prefpane. But not just leave the option as default.

**Comment by Charlyo** [comment]
If the majority of the systems still overheat at HFSP 1, then theres no point on letting the user select HFSP 1 and not 0.

**Comment by zhen-zen** [comment]
Even at the lowest level, it's still possible to recover after BDPROCHOT. However, ambient cooling could just raise above TJUNCTION and take the CPU down.
Since I'm not a thinkpad owner, maybe I will wait for other people's opinions.

**Comment by benbender** [comment]
@Charlyo what is your actual usecase? I don't see any real benefit atm.

**Comment by Charlyo** [comment]
@benbender my actual T460 has a dual core i5 6200U that only goes up to 2.8Ghz. Even at full load its temperature stays at ~70° C withou fans turned on. Also the actual fan curve is too agresive, turning the fans on just at 45°.

**Comment by zhen-zen** [comment]
Does this work for you? https://github.com/zhen-zen/YogaSMC/commit/eb57c2557186b1283eeeeefaacd9bc6e5a5306ce

**Comment by Sniki** [comment]
Fan curve is something i would like to address on my laptops as well.
Especially on the X240, a dual core i5-4300U Haswell laptop with an aggressive fan curve as well, it tends to kick in often without like any reason.
It hits the battery like that and hits the comfort of using it on a calm environment.

**Comment by Charlyo** [comment]
> Does this work for you? [eb57c25](https://github.com/zhen-zen/YogaSMC/commit/eb57c2557186b1283eeeeefaacd9bc6e5a5306ce)

That's more than fine for me @zhen-zen! Again, thank you for your time!

**Pull request closed without merging**
