### PR TITLE
YogaHIDD: made initVPC() for _DSM not mandatory

### PR DESCRIPTION
**Pull request by zhen-zen**

### CODE REVIEW

**Comment by zhen-zen** [comment]
@m0d16l14n1

**Comment by m0d16l14n1** [comment]
Can you please send me test build? I am trying to build it myself, but I got that error while trying to compile it

`/Users/b0ltun/Downloads/YogaSMC-hidd-fix/YogaSMC/YogaBaseService.hpp:12:10: 'Headers/kern_version.hpp' file not found`

**Comment by zhen-zen** [comment]
You can get prebuilt version here https://github.com/zhen-zen/YogaSMC/actions/runs/376984740

**Comment by m0d16l14n1** [comment]
> You can get prebuilt version here https://github.com/zhen-zen/YogaSMC/actions/runs/376984740. And check `building` section in readme if you want to build it your self.

Thanks! Sorry, I am still not so good at that things. Will test it now

**Comment by m0d16l14n1** [comment]
@zhen-zen still no brightness control, but fn mask error disappeared. Here the log test build

`[    2.427817]: YSMC - Debug: YogaHIDD::(null) Initializing
[    2.427836]: YSMC - Debug: YogaHIDD::HIDD Probing
[    2.427926]: YSMC - Debug: YogaHIDD::HIDD PNP0C09 available at H_EC
[    2.428313]: YSMC - Debug: YogaHIDD::HIDD Starting
[    2.428387]: YSMC - Debug: YogaHIDD::HIDD powerState 1 : on
[    3.827487]: YSMC - Debug: YogaHIDD::HIDD Notification consumer published: VoodooI2CPrecisionTouchpadHIDEventDriver
[    4.280913]: YSMC - Debug: YogaHIDD::HIDD Notification consumer published: ApplePS2Controller
[    4.292074]: YSMC - Debug: YogaHIDD::HIDD Notification consumer published: ApplePS2Keyboard`

**Comment by zhen-zen** [comment]
Can you take a screenshot of `YogaHIDD` ioreg?

**Comment by m0d16l14n1** [comment]
> Can you take a screenshot of `YogaHIDD` ioreg? And have you removed related rename?

Yes, rename patches and SSDT disabled in config.plist

Here is screenshot:

image

**Comment by zhen-zen** [comment]
It's weird. It should at least return "Failed to obtain valid fn mask, evaluating methods directly" since yours don't have `_DSM` method. And `HEBC` is not present.

**Comment by m0d16l14n1** [comment]
> Wait, please switch to IOService plane.

I don't have YogaHIDD here at all. Only HIDD itself

**Comment by zhen-zen** [comment]
It should attach to `HIDD`, that's the intention of `IOPropertyMatch`.

**Comment by m0d16l14n1** [comment]
> It should attach to `HIDD`, that's the intention of `IOPropertyMatch`.

image

**Comment by zhen-zen** [comment]
Can you try the new commit? Prebuilt version will be ready in 2-3 minutes.

**Comment by m0d16l14n1** [comment]
> Can you try the new commit? Prebuilt version will be ready in 2-3 minutes.

Sure

**Comment by m0d16l14n1** [comment]
@zhen-zen - same log as previous one, no YogaHIDD under HIDD device in IOreg :(

**Comment by zhen-zen** [comment]
Can you also upload logs containing `ACPI`?

**Comment by m0d16l14n1** [comment]
@zhen-zen sure. In one of the logs you will see stuff about lid sometimes not working (closing it won't work to go to sleep mode) - I mentioned that stuff [here](https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/issues/7). By the way, in that log - [LID not working.log](https://github.com/zhen-zen/YogaSMC/files/5579195/LID.not.working.log) i found something related to HIDD, but I was using previous test build, not latest.

[ACPI.log](https://github.com/zhen-zen/YogaSMC/files/5579190/ACPI.log)
[ACPI1.log](https://github.com/zhen-zen/YogaSMC/files/5579191/ACPI1.log)

**Comment by zhen-zen** [comment]
Sorry for the inconvenience, it should works now.

**Comment by m0d16l14n1** [comment]
> Sorry for the inconvenience, it should work now.

Yes, it's working now, I see it IOreg, but still kinda strange, heh. Fn+F5 is lowering brightness, but Fn+F6 is not working. Fn+F6 is only working at login screen. Power button is not working usually, but now it's sometimes working, sometimes not

Here is the log

[Yoga.log](https://github.com/zhen-zen/YogaSMC/files/5579236/Yoga.log)

**Comment by m0d16l14n1** [comment]
Some update, just log out and check Fn+F6 - it's working, once I logged in - it's not working. Power button is working once I click it after logging. If I wake laptop from sleep - power button is not responsive. I am really not sure if power button is controlled via YogaSMC, but previously without that kext it wasn't working at all

**Comment by m0d16l14n1** [comment]
One more update - I was playing with the keys now, once I hit Fn+F6 - "Are you sure you want to shut down your computer now?" window appeared

**Comment by zhen-zen** [comment]
It's quite weird that only few keys requires user space client. While others including what you have just mentioned, should work for both.

**Comment by zhen-zen** [comment]
My bad, forgot another break here.

**Comment by m0d16l14n1** [comment]
> My bad, forgot another break here.

Same thing now. Fn+F6 working on login screen, but on at the desktop screen. Power button is not responsive at all now again (still not sure if it's kext thing or just my ACPI problem)
[Yoga.log](https://github.com/zhen-zen/YogaSMC/files/5579258/Yoga.log)

**Comment by zhen-zen** [comment]
Can you get `Karabiner-EventViewer.app` and check what's sent after login?

**Comment by zhen-zen** [comment]
It's quite weird that in your last log, only `argument=0x00c0` is sent for brightness and other HID events. However, `0x00ce/0x00cf` for power button does not present. But they appeared in the first `Yoga.log`.

**Comment by m0d16l14n1** [comment]
> But they appeared in the first `Yoga.log`.

Yeah, in previous test build power button worked (turned off display if I just click it, but only for the first time) and that window appeared somehow when I clicked Fn+F6

**Comment by m0d16l14n1** [comment]
> It's quite weird that in your last log, only `argument=0x00c0` is sent for brightness and other HID events. However, `0x00ce/0x00cf` for power button does not present. But they appeared in the first `Yoga.log`.

Do you need DSDT dump? Maybe something wrong in it?

**Comment by zhen-zen** [comment]
I grabbed your diagnosis file from VoodooI2C but there's nothing strange. Same as how `_Q13/_Q14` rename works, everything should go through ACPI and notify the driver. Can you try with SIP off?

**Comment by Ab2774** [comment]
Hi @zhen-zen, I have a similar problem to @m0d16l14n1 where the power button isn't working, strangely, in Clover, it's working fine.
Here's a picture of IOReg, should I add a fake `HIDD` device or to try anything else?
Thanks in advance
PWRB

**Comment by zhen-zen** [comment]
Although you haven't upload any DSDT/SSDTs dump, I don't think there would be valid `HIDD` device when another hotkey subsystem exist. Fake ones won't work since they could not get notify at ACPI level.

**Comment by m0d16l14n1** [comment]
> I grabbed your diagnosis file from VoodooI2C but there's nothing strange. Same as how `_Q13/_Q14` rename works, everything should go through ACPI and notify the driver. Can you try with SIP off?

Sure, i will try it

**Comment by m0d16l14n1** [comment]
@zhen-zen managed to disabled SIP, seems to work better now. Power button is fully responsive and stable, Fn+F5 stable too. Fn+F6 is still working only at login screen
[YogaDISABLEDsip.log](https://github.com/zhen-zen/YogaSMC/files/5582929/YogaDISABLEDsip.log)

**Comment by zhen-zen** [comment]
I have no idea why SIP will make a difference although others report so.

There's no `index 4 results 0x14`(KEY_BRIGHTNESSDOWN) line after 70 secs, only `results 0x13`(KEY_BRIGHTNESSUP) appears there. However, you mentioned "Fn+f5 - -brightness; Fn+f6 - +brightness". Am I missing some point?

**Comment by Ab2774** [comment]
> Although you haven't upload any DSDT/SSDTs dump, I don't think there would be valid `HIDD` device when another hotkey subsystem exist. Fake ones won't work since they could not get notification at ACPI level.

Hi, here's my DSDT dump, I really hope that there's a fix for my problem as Clover sucks with Big Sur but the power button is working well there, thanks for your help.
[DSDT.aml.zip](https://github.com/zhen-zen/YogaSMC/files/5587276/DSDT.aml.zip)

**Comment by m0d16l14n1** [comment]
> There's no `index 4 results 0x14`(KEY_BRIGHTNESSDOWN) line after 70 secs, only `results 0x13`(KEY_BRIGHTNESSUP) appears there. However, you mentioned "Fn+f5 - -brightness; Fn+f6 - +brightness". Am I missing some point?

Yes, Fn+F5 is -brightness and Fn+F6 is +brightness. For that log i was pressing Fn+F6 much more at the end, just to be sure it's captured correctly, not buggy like it was previously (shutdown menu sometimes appeared if i click Fn+F6).

**Comment by zhen-zen** [comment]
> Hi, here's my DSDT dump, I really hope that there's a fix for my problem as Clover sucks with Big Sur but the power button is working well there, thanks for your help.
> [DSDT.aml.zip](https://github.com/zhen-zen/YogaSMC/files/5587276/DSDT.aml.zip)

Drivers will follow the same implementation since the ACPI table is the same and nothing's strange there. Maybe something's different in UEFI environment but I don't know much about it.


> Yes, Fn+F5 is -brightness and Fn+F6 is +brightness. For that log i was pressing Fn+F6 much more at the end, just to be sure it's captured correctly, not buggy like it was previously (shutdown menu sometimes appeared if i click Fn+F6).

Have you monitored it with `Karabiner-EventViewer`? Also debug version of VoodooPS2 will log each keypress.

**Comment by m0d16l14n1** [comment]
> Have you monitored it with `Karabiner-EventViewer` mentioned above?

Hm, nope, you told me that i don't need to download it. I can download it and check it

**Comment by m0d16l14n1** [comment]
@zhen-zen here is report from Karabiner app. F14 is brightness down, F15 is brightness up here. Brightness up is not working. Also attaching debug log

type:key_down        code:105        name:f14             misc:
type:key_up          code:105        name:f14             misc:
type:key_down        code:106        name:f15             misc:
type:key_up          code:106        name:f15             misc:
type:key_down        code:106        name:f15             misc:
type:key_up          code:106        name:f15             misc:
type:key_down        code:106        name:f15             misc:
type:key_up          code:106        name:f15             misc:
type:key_down        code:105        name:f14             misc:
type:key_up          code:105        name:f14             misc:
type:key_down        code:105        name:f14             misc:
type:key_up          code:105        name:f14             misc:
type:key_down        code:105        name:f14             misc:
type:key_up          code:105        name:f14             misc:
type:key_down        code:106        name:f15             misc:
type:key_up          code:106        name:f15             misc:
type:key_down        code:106        name:f15             misc:
type:key_up          code:106        name:f15             misc:

[YogaDISABLEDsip.log](https://github.com/zhen-zen/YogaSMC/files/5587792/YogaDISABLEDsip.log)

**Comment by m0d16l14n1** [comment]
@zhen-zen omg, i am stupid. heh. I just restored defaults settings into Keyboard > Shortcut. F14 was brightness low and F12 was brightness up. So i restored settings to default (F14 and F15) and now Fn+F6 working like it should

**Comment by m0d16l14n1** [comment]
So, now brightness keys working fully like they should and power button too. Still Fn+F12 (num lk) and Fn+F1 (wifi switch) but i am not sure if i really need that to work under macOS. Now i need disable Fn+F11 somehow, because it's working like Fn+F5 now (-brightness)

**Comment by zhen-zen** [comment]
Glad to hear it works.

**Comment by zhen-zen** [comment]
> > Although you haven't upload any DSDT/SSDTs dump, I don't think there would be valid `HIDD` device when another hotkey subsystem exist. Fake ones won't work since they could not get notification at ACPI level.
> 
> Hi, here's my DSDT dump, I really hope that there's a fix for my problem as Clover sucks with Big Sur but the power button is working well there, thanks for your help.
> [DSDT.aml.zip](https://github.com/zhen-zen/YogaSMC/files/5587276/DSDT.aml.zip)

Some general advice to try: rename your `_Q32` and replace `Notify (PWRB, 0x80)` with `Notify (^^^GFX0.DD1F, 0x87)` in it. If your power button could not trigger brightness - while brightness - can, then I have no idea.

**Comment by m0d16l14n1** [comment]
> Glad to hear it works. By the way can you try it again with SIP enabled?

Sure, i will try it again

**Comment by m0d16l14n1** [comment]
@zhen-zen it's weird, but it's seems working now even with SIP enabled. Strange, heh. Again, thanks for your hard work and help. My hackintosh is becoming more stable to use (still touchpad dead after sleep/problems with sound/lid issue)!

**Comment by zhen-zen** [comment]
I'm sorry to bother you again. After merging it to master branch, I found a flaw and fixed it in 66db486. Theoretically it should break nothing, can you test it out when you have time?

**Comment by Ab2774** [comment]
> Some general advice to try: rename your `_Q32` and replace `Notify (PWRB, 0x80)` with `Notify (^^^GFX0.DD1F, 0x87)` in it. If your power button could not trigger brightness - while brightness - can, then I have no idea. And attach a copy of ioreg as well.

Hi, thanks for your help, unfortunately, it didn't work, I don't know what else to try, here's a copy of my IOReg.
I still haven't figure out how to fix Big Sur's wake, where [USBWakeFixup](https://github.com/osy86/USBWakeFixup) is required to avoid a second keyboard click to light up the screen.
Thanks
[IOReg.zip](https://github.com/zhen-zen/YogaSMC/files/5594423/IOReg.zip)

**Comment by m0d16l14n1** [comment]
> I'm sorry to bother you again. After merging it to master branch, I found a flaw and fixed it in [66db486](https://github.com/zhen-zen/YogaSMC/commit/66db4862a3fd4fbced06cf77eb6133e07aaf8090). Theoretically it should break nothing, can you test it out at your convenience?

Sure, i will test the build of latest commit now

**Comment by zhen-zen** [comment]
> Hi, thanks for your help, unfortunately, it didn't work, I don't know what else to try, here's a copy of my IOReg.

It sounds like the `_Q32` event is not called. Maybe something's wrong in UEFI environment or setting up GPE trigger. I'm not familiar with that.

> I still haven't figure out how to fix Big Sur's wake, where [USBWakeFixup](https://github.com/osy86/USBWakeFixup) is required to avoid a second keyboard click to light up the screen, but doing so breaks GPRW wake causing an instant wake.

Laptops usually have valid EC. And per description, yours shouldn't use that kext, which approach goes through GPE and could mess up with former issue. Please use forum for support.

**Comment by m0d16l14n1** [comment]
@zhen-zen Power button seems to be broken again. With SIP enabled or disabled it's not working. 

[yoga.log](https://github.com/zhen-zen/YogaSMC/files/5594607/yoga.log)

**Comment by m0d16l14n1** [comment]
> @zhen-zen Power button seems to be broken again. With SIP enabled or disabled it's not working.

Made a couple reboots, now it's working again. Heh.
[yoga.log](https://github.com/zhen-zen/YogaSMC/files/5594630/yoga.log)

**Comment by m0d16l14n1** [comment]
> I'm sorry to bother you again. After merging it to master branch, I found a flaw and fixed it in [66db486](https://github.com/zhen-zen/YogaSMC/commit/66db4862a3fd4fbced06cf77eb6133e07aaf8090). Theoretically it should break nothing, can you test it out at your convenience?

If you ever need to test anything - feel free to ping me, i will test any of your work without any problem. Thanks again!

**Comment by zhen-zen** [comment]
It's weird that power button doesn't work reliably. Maybe the issue has connection to the ones @Ab2774 got. On ACPI level, everything looks good but the specific `_Qxx` was never called. Probably Clover might work, but I haven't come up with the possible culprit / quirks that would fix it.

**Comment by Ab2774** [comment]
Hi @zhen-zen, thanks for your help, I really appreciate it.

**Comment by m0d16l14n1** [comment]
@zhen-zen hello! Sorry for maybe annoying you again, i have questions about some of the FN Keys. 

I have Fn+F1 (disable-enable WiFi) and Fn+Space (disable-enable trackpad). I also has Fn+F9 (brightness for keyboard)

So the problem is disabling touchpad and brightness for keyboard keys are working great, even without patches/using YogaSMC. But Fn+F1 is not working at all. I was trying to bind that Fn+f1 via karabiner but it's not seeing any events while i pressing that combo. So the questions are:

1) Is it possible to make that Fn+F1 working? (it's seems working okay under Windows/Linux btw)
2) Is it possible to get like HUD appearing on pressing keyboard brightness or touchpad switch combos? The same one like you get if you press Fn keys for volume/screen brightness. I found LGgramAssistant/ThinkPadAssistant, but i am not sure if it's possible to adopt it for my laptop and my Fn keys. 

So, i am not actually asking you for doing that, i am just interested if it's all possible or not. If yes - what is the way to do it? I was told about VoodooPS2 remapping and stuff, but i am not sure if it's really the right way, because BrightnessKeys.kext didn't work for me.

**Comment by zhen-zen** [comment]
Trackpad and keyboard brightness control are vendor-specific and not supported by this driver yet. If the prompt works in linux, it's possible to port related code.

However, airplane mode toggle is more generic and there's no mapping to an existing key. For that, you will need the NC app although it's designed to work with more complicated key events.

**Comment by m0d16l14n1** [comment]
> Trackpad and keyboard brightness control are vendor-specific and not supported by this driver yet. If the prompt works in linux, it's possible to port related code.

Thanks for the answer. Right now i found one strange thing. With YogaSMC kext lid sleep sometimes not working. It's not going to sleep (seems to be the problem with YogaHIDD bounding to touchpad actually, but i am not sure). I did disable it now, still testing but now sleep from lid working. With YogaSMC sleep from "fn key" or Apple logo > Sleep or power button - working okay, only problem with lid sleeping. I don't know if it's possible to debug that somehow, or if it's possible to disable bounding YogaHIDD to touchpad (to VoodooI2CHID)

**Comment by zhen-zen** [comment]
Can you run `Karabiner-Eventviewer` in `Karabiner-Elements` and find if lid sleep will produce a key stroke?  HID event from the kext might prevent the system from sleeping.

**Comment by m0d16l14n1** [comment]
> Can you run `Karabiner-Eventviewer` in `Karabiner-Elements` and find if lid sleep will produce a key stroke? HID event from the kext might prevent the system from sleeping.

Tested right now, there are no key strokes triggered by lid sleep. Actually, i think i found the issue which caused lid sleep to fail. That was Thunderbolt 3 USB port - it wasn't mapped. So i have tested it for 2 days now - i don't see any problem now. Problem is gone (power button is working, brightness keys too). 

Will dig into getting other Fn keys working. Thanks and sorry for that issue!

**Pull request merged**
