### PR TITLE
IdeaVPC: only check brightness with poller

### PR DESCRIPTION
**Pull request by zhen-zen**
Close #20 
Close #22

### CODE REVIEW

**Comment by marianopela** [comment]
[Here](https://github.com/zhen-zen/YogaSMC/files/5683031/poll-only.bkeys.zip) is a screen recording while rapidly pressing brightness keys 8 times in a row, then stopping for a bit, then pressing them again 8 times, for a total of 4 turns (down and up again). In one I'm letting YogaSMCNC open, and in the other not. 

I'll post the same test on latest master commit shortly, for comparison

**Comment by marianopela** [comment]
Here are [master](https://github.com/zhen-zen/YogaSMC/files/5683048/master.mov.zip) and [master with NC](https://github.com/zhen-zen/YogaSMC/files/5683045/master.with.NC.mov.zip)

In the latter NC continued showing wrong icons long after I stopped the recording (keyboard backlight, touchpad on/off and mic on/mute)

**Comment by zhen-zen** [comment]
Event 0x0c / 12 is not documented in https://github.com/torvalds/linux/blob/master/drivers/platform/x86/ideapad-laptop.c#L659. Before figuring out the event, it can be disabled by manually edit `~/Library/Preferences/org.zhen.YogaSMC.plist` and change `display` to 0.

You don't need the poller since yours already have working brightness key per ACPI spec. Have you tried the Alter variant?

**Comment by marianopela** [comment]
> it can be disabled by manually edit `~/Library/Preferences/org.zhen.YogaSMC.plist` and change `display` to 0.

Do you mean by adding a new entry with ID 12 and setting its `display` to 0?
> Have you tried the Alter variant?

I've been using it for the past month and wanted to give the normal version another try. They seem to behave the same way
The only strange behavior I still experience is choppy laggy brightness variation. Just to remind you, it only lags when using YogaSMC, and I was trying to understand why
> Edit: just found some note that Event 0x0c could be keyboard backlight / LED changes. How's that working on your laptop?

Do you mean if it's recognized by NC? It takes a 2/3 seconds (at least) to get recognized, and it's not really reliable. Sometimes it is read as event 0x09

**Pull request merged**
