### PR TITLE
Pane: fix erratic mute and MicMute selection in LED Automation

### PR DESCRIPTION
**Pull request by junaedahmed**
I think this typo is causing erratic switching to mute when I select micMute.

### CODE REVIEW

**Comment by zhen-zen** [comment]
Thank you for catching that. And what's the new item in `.gitignore`?

**Comment by junaedahmed** [comment]
> Thank you for catching that. And what's the new item in `.gitignore`?

I am getting a directory with named Index/datastore with lots of folders an files. I don't know if this is related to exFAT file system.

**Comment by Charlyo** [comment]
If I'm not mistaked this is related to xcodebuild storing stuff for subsequent builds.

**Comment by zhen-zen** [comment]
iirc those indexes are always in `~/Library/Developers`. Anyway, I will just merge it.

**Pull request merged**
