### PR TITLE
Replace spotlight with siri for F10 key

### PR DESCRIPTION
**Pull request by junaedahmed**
As spotlight has already a most used global hotkey. It is more reasonable to change F10 to a dedicated siri hotkey. It also modifier key independent so if someone change modifier key behavior it will still work.

### CODE REVIEW

**Comment by zhen-zen** [comment]
The configurations are already separated into `Configuration.swift`. And I believe it's user's choice to change the their configuration, and the preset should just follow the keys' behavior under Windows. Also regarding that AppleScript, the action is based on the location Siri icon in menubar, which might not be moved or not exist. Since Siri is an individual app, `tell application "Siri" to activate` should work better.

**Comment by junaedahmed** [comment]
I know It's user's choice. I wanted to change the default behavior with Thinkpads one as on windows it opens cortana by this key.

**Comment by junaedahmed** [comment]
And sorry for this bad as I did a merge from this branch to master it also changed here too.

**Comment by zhen-zen** [comment]
> I know It's user's choice. I wanted to change the default behavior with Thinkpads one as on windows it opens cortana by this key.

Since other keys have defined usage, I think both this key and the star / fav one are good starting point for learning customization. The former one could launch built-in routine and the latter one is for script in `option` field.

**Comment by SukkaW** [comment]
> I wanted to change the default behavior with Thinkpads one as on windows it opens Cortana by this key.

No. It is only the behavior of old ThinkPad models. Newer ThinkPad models have the `F10` key for toggling Bluetooth. And newest ThinkPad models have the `F10` key for the phone.

FYI:

T450 (2015) Keyboard:

image

T480 (2018) Keyboard: 

image

T14 (2020) Keyboard:

image

**Comment by zhen-zen** [comment]
Alright, I will just merge it and revert the addition in `AppDelegate`. Bluetooth key has another notification code.

**Comment by junaedahmed** [comment]
> > I wanted to change the default behavior with Thinkpads one as on windows it opens Cortana by this key.
> 
> @junaedahmed
> 
> No. It is only the behavior of old ThinkPad models. Newer ThinkPad models have the `F10` key for toggling Bluetooth. And newest ThinkPad models have the `F10` key for the phone.
> 
> FYI:
> 
> T450 (2015) Keyboard:
> 
> image
> 
> T480 (2018) Keyboard:
> 
> image
> 
> T14 (2020) Keyboard:
> 
> image

It's not a problem same key on different model produce different Event. So it will only effect F10 key with search icon printed on it. Others models with bluetooth and star in F10 key will be fine.

**Pull request merged**
