### PR TITLE
Updated icons and copyright year

### PR DESCRIPTION
**Pull request by mackonsti**
Hi @zhen-zen I took the liberty of updating the icons for the PreferencePane and the menu icons, including the respective Info.plist files. Also, I updated for you the Copyright years.

The new release as you are aware, still has the bug that I reported some time ago https://github.com/zhen-zen/YogaSMC/issues/159 and as I have friends at work that know Xcode, I will ask them if they know how to smoothly quit a Preference Pane to avoid this issue in the next release, hopefully...

Hope you like my work and approve this request! Cheers

P.S. Obviously these couple of changes were already tested on my IdeaPad 😄

### CODE REVIEW

**Comment by zhen-zen** [comment]
Thanks a lot! I will check it out tomorrow. For the prefpane, the issue happens since it need to refresh the status frequent. And so far I didn't find a good example or tutorial. One possible solution is, to disable status update, if something changed, you need to close the prefpane window completely and reopen that. What do you think about it?

**Comment by mackonsti** [comment]
Compared to a crashing pane, I prefer to refresh to be honest.
Because don't forget that the PrefPane is also opened by YogaSMCNC from menu...
Let's try that and see how it goes!  Have a nice Sunday evening.

**Comment by zhen-zen** [comment]
Just downloaded the icns... I suppose there's copyright issue with that.

**Comment by mackonsti** [comment]
OK @zhen-zen I understand totally. Allow me to create some custom icons then?

**Comment by mackonsti** [comment]
I was looking for "gears" icon (denoting "Settings" as usual) and came across the car's gear, so instead of the numbers I thought of adding a red dot (over the numbers) that makes people think of the Lenovo red, what do you think? I didn't add anything on the red dot, on purpose... Would you like this instead, @zhen-zen ?

GearRed_256px

**Comment by zhen-zen** [comment]
That's a good metaphor. Although this driver is not only for Thinkpad series, I agree with that.

**Comment by mackonsti** [comment]
Thanks, not really related to ThinkPad but all Lenovo due to the red colour 😄 (as Lenovo logo switched to red...)
Shame that I missed your release, I had no idea you'd plan to do such release 30mins ago 😆 
I will provide the icons for you in the next couple of days, thanks for your feedback @zhen-zen !

**Pull request closed without merging**
