### PR TITLE
Updated copyright years and Preferences/Application icons

### PR DESCRIPTION
**Pull request by mackonsti**
Updated copyright years;
Updated Preferences & Application icons.

### CODE REVIEW

**Comment by mackonsti** [comment]
Hello @zhen-zen I believe I have done the procedure correctly, new icons updated as discussed and kept the updated 2022 copyright year. Take care.

**Comment by zhen-zen** [comment]
You might need to change the name (tiff->icns) in `project.pbxproj` as well

**Comment by mackonsti** [comment]
Hi @zhen-zen thanks, I was under the impression you'd include them and rebuild the project yourself, to validate. I do not have Xcode installed, and all edits were manually and carefully done via BBEdit. The change from tiff -> icns is done, but I worry about **where to include the other icon** in the `./YogaSMCNC/Resources/YogaSMCNC.icns` application? I do not want to add stuff to `project.pbxproj` so perhaps you'd like to add it on your Xcode when you have time? Thanks.

**Comment by zhen-zen** [comment]
Thanks! The icon for prefpane is ready and I will update the app icon

**Comment by mackonsti** [comment]
Thanks @zhen-zen for your help and accepting this merge request! Talk to you soon!

**Pull request merged**
