### PR TITLE
ThinkVPC: support yoga mode detection

### PR DESCRIPTION
**Pull request by zhen-zen**

### CODE REVIEW

**Comment by zhen-zen** [comment]
@antoniomcr96 @KirisameMarisaa Can you try this build?

**Comment by antoniomcr96** [comment]
Thanks for your interest. Unfortunately I don't have Xcode available on this machine (low space). Can you zip it for me?

**Comment by zhen-zen** [comment]
You can download prebuilt version in GitHub Actions: https://github.com/zhen-zen/YogaSMC/actions/

**Comment by antoniomcr96** [comment]
It wooorks! I made an image, you can use it if you like it
TabletMode

**Comment by zhen-zen** [comment]
Glad to hear that works. Can you suggest where to use that image?

**Comment by antoniomcr96** [comment]
> Glad to hear that works. Can you suggest where to use that image?

“Event Tablet Mode”

**Comment by zhen-zen** [comment]
Maybe just show image of different modes? I'm considering get something like
Screen Shot

**Comment by zhen-zen** [comment]
Alright, I will just merge it for now. Please left further comment in #68.

**Pull request merged**
